adults = ['If you were in a circus, which character would you be?', 'What is the worst advice you have given?', 'What is one thing you should never say at a wedding?', 'What is the worst pickup line you have ever heard?', 'If you could only store one type of food in your pocket, what would you carry?', 'What is the worst present you have ever received and why?', 'If you were a farm animal, which would you be and why?', 'What is the worst first date you have ever been on?', 'Have you ever stalked someone on social media?', 'What is the best part about taking a selfie?', 'What is your favorite celebrity scandal?', 'If you could do anything illegal without getting caught, what would you do?', 'What is the weirdest food combination you’ve ever tried?', 'Did you have an imaginary friend? What was his/her name?', 'Have you ever had a dream where everyone was in their underwear?', 'Who’s your favorite comedian?', 'Have you ever been on a blind date?']
kids = ['What is your very favorite letter of the alphabet? Why?', 'If someone gave you 20 dollars, what would you buy with it?', 'If you had a chance to eat dessert for breakfast every day, what dessert would you choose?', 'What is the first thing you think about when you wake up in the morning?', 'Which animal at the zoo do you like best?', 'If your friend is sad, what do you do to make them feel better?', 'If you had the opportunity to invent a new ice cream flavor, what would it be?', 'What is the silliest thing someone has ever said to you?', 'What’s your idea of a perfect playground?', 'What’s your favorite word?', 'Would you switch roles with your parent if you had the chance?', 'When was the last time you used the words “thank you”?', 'If you had a robot for the entire day, what would you ask it to do?', 'Do you prefer cold weather or hot weather?', 'If you never had to eat one vegetable, which would it be?', 'What was the last thing that made you smile?', 'What is your favorite part about school? Your least favorite?', 'How do you make friends?', 'Who makes you laugh the most?']
deep = ['What are the top three things on your bucket list?', 'How do you think you will die?', 'What has been the lowest point of your life?', 'If you could ask for a miracle, what would it be?', 'Where do you see yourself in five years?', 'What is the biggest risk you’ve ever taken?', 'What would your ideal life look like?', 'If someone gave you an envelope with your death date inside of it, would you open it?', 'When have you been the most happy?', 'Do you know anyone who is living their life to the fullest?', 'What is your idea of the perfect day?', 'Who has been the most influential person in your life and why?', 'What book had a big influence on you?', 'Do you think your priorities have changed since you were younger?', 'What is the most memorable lesson you learned from your parents?', 'What does success mean to you?', 'What is the most difficult thing you’ve ever done?', 'What scares you most about your future?', 'What keeps you up at night?']
couples = ['What do you think people need to know about each other before they get married?', 'What makes you very sentimental?', 'What do I do that makes you smile?', 'What is the best or worst trait you inherited from your parents?', 'What is your funniest memory of our dates?', 'Who was your first crush and why?', 'What three things do you want to be remembered for?', 'Is there a dream you’ve always had?', 'What is something you’ve always wanted to do, but are scared to?', 'What gives you butterflies?', 'What do you consider most romantic?', 'What motivates you most in life?', 'What things do you consider to be relationship deal breakers?', 'Do you think arguing is part of a relationship?', 'If we were to raise children, what are the most important things you would want them to learn?', 'How would you describe our relationship?', 'How would your partner describe you?', 'Do you consider yourself a spiritual person? How?', 'If you made a bucket list for us, what would you add to it?', 'How has our relationship changed since we started dating?', 'What do I do that comforts you the most?', 'What makes you feel discouraged?', 'What is a significant event that has changed you?', 'If your life was a movie, which celebrity would play you?']
family = ['What time period would you travel to?', 'What is one thing you can’t live without?', 'What is your least favorite chore?', 'What is your earliest memory?', 'Where do you want to go on the next family vacation?', 'Who are you most thankful for and why?', 'Where do you want to go on the next family vacation?', 'What was the biggest punishment you’ve ever received?', 'What’s the nicest thing a family member has ever done for you?', 'What would be the first thing you would do if you traded places with your family member?', 'If you could get all your family members to donate to a charity, what would it be and why?', 'What instrument would you like to play?', 'What makes you most proud?', 'What three things are you most grateful for?', 'Who do you count on the most for help?', 'What would make you (if parent) most upset? A tattoo, a nose ring or a bad boyfriend/girlfriend?', 'What would be your ideal day?', 'What makes you the happiest?', 'If you could spend an entire day with a family member, who would it be and why?', 'If you could be an animal, what would it be and why?', 'If you could be any age, what age would you choose?', 'What’s one thing you’ve won and how did you win it?', 'What did you think was the most challenging part of being a kid?', 'When is the last time you laughed so hard that you cried?']
together = ['How long can you go without checking your phone?', 'Have you ever really kept a New Year’s resolution?', 'What bad habits do you wish you could stop?', 'Do you have a morning ritual?', 'Have you ever been stalked on social media?', 'Do you prefer polaroid or digital cameras?', 'If someone offered to tell you your future, would you accept it?', 'Who’s your biggest hero?', 'Have you ever stolen anything?', 'If you were to remove one social media app from your phone, which would it be and why?', 'What is your most embarrassing moment?', 'What is your most embarrassing moment?', 'If you were on death row, what would your last meal be?', 'If you could sit down with your 13-year old self, what would you say?', 'If you could only pack one thing for a trip (besides clothing) what would it be?', 'What makes you really angry?', 'What is your spirit animal?', 'What would be the title of your memoire?', 'What’s your guilty pleasure?']
resto = ['If you could have dinner with anyone living or not, who would it be?', 'Are you a cat person or a dog person?', 'What is the silliest thing you’ve posted online?', 'What was your worst wardrobe mistake?', 'What is the best restaurant you’ve been to?', 'What is your favorite kitchen smell?', 'When you die, what do you want to be reincarnated as?', 'What is your favorite guilty pleasure TV show?', 'What was your worst “foot in mouth” moment?', 'Who would you swap lives with for a day?', 'If you could live anywhere in the world, where would it be?', 'What is the strangest gift you have ever received?', 'What is the funniest gift you have ever given?', 'What are three fun facts about yourself?', 'What’s the best compliment you’ve ever received?', 'Would you rather be invisible or have X-ray vision?', 'If you could only save one item from a house fire, what would it be?', 'What is the one food you could eat for the rest of your life?', 'If you won the lottery, what would be your first big splurge?', "How do you know this bot's creator?", 'If you won the lottery, what would be your first big splurge?', 'What’s one movie you could watch over and over?', 'Where’s the most exotic place you’ve ever been?', 'If you could have picked your own name, what would it be?']
randlist = ['What was the last funny video you saw?', 'What do you do to get rid of stress?', 'What is something you are obsessed with?', 'What three words best describe you?', 'What would be your perfect weekend?', 'What’s your favorite number? Why?', 'What are you going to do this weekend?', 'What’s the most useful thing you own?', 'What’s your favorite way to waste time?', 'What do you think of tattoos? Do you have any?', 'Do you have any pets? What are their names?','Where did you go last weekend? / What did you do last weekend?', 'What is something popular now that annoys you?', 'What did you do on your last vacation?', 'When was the last time you worked incredibly hard?', 'Are you very active, or do you prefer to just relax in your free time?', 'What do you do when you hang out with your friends?', 'Who is your oldest friend? Where did you meet them?', 'What’s the best / worst thing about your work/school?', 'If you had intro music, what song would it be? Why?', 'What were you really into when you were a kid?', 'If you could have any animal as a pet, what animal would you choose?', 'Have you ever saved an animal’s life? How about a person’s life?', 'f you opened a business, what kind of business would it be?', 'Who is your favorite entertainer (comedian, musician, actor, etc.)?', 'Are you a very organized person?', 'What is the strangest dream you have ever had?', 'What is a controversial opinion you have?', 'Who in your life brings you the most joy?', 'Who had the biggest impact on the person you have become?', 'What is the most annoying habit someone can have?', 'Where is the most beautiful place you have been?', 'Where do you spend most of your free time/day?', 'Who was your best friend in elementary school?', 'How often do you stay up past 3 a.m.?', 'What’s your favorite season? Why?', 'Which is more important, having a great car or a great house? Why?', 'What animal or insect do you wish humans could eradicate?', 'Where is the most beautiful place near where you live?']
randlist2 = ['What do you bring with you everywhere you go?', 'How much time do you spend on the internet? What do you usually do?', 'What is the most disgusting habit some people have?', 'Where and when was the most amazing sunset you have ever seen?', 'Which recent news story is the most interesting?', 'Where is the worst place you have been stuck for a long time?', 'If you had to change your name, what would your new name be?', 'What is something that really annoys you but doesn’t bother most people?', 'What word or saying from the past do you think should come back?', 'How should success be measured? And by that measurement, who is the most successful person you know?', 'What is your guilty pleasure?', 'Was there ever an event in your life that defied explanation?', 'If you could learn the answer to one question about your future, what would the question be?', 'Has anyone ever saved your life?', 'What benefit do you bring to the group when you hang out with friends?', 'How often do you curse? And what’s your go-to string of curse words?', 'What trends did you follow when you were younger?', 'What do you fear is hiding in the dark?', 'What was the best period of your life so far? What do you think will be the best period of your entire life?', 'What do you do to improve your mood when you are in a bad mood?', 'What is the silliest fear you have?', 'What are some things you want to accomplish before you die?', 'What is the best room in your house? Why?', 'Who is someone popular now that you really like? Why do you like them so much?', 'Where is the best place to take a date?', 'What smell brings back great memories?', 'What’s the best pet name you can come up with for a specific type of pet? (Like these orange cat names.)', 'How often do you help others? Who do you help? How do you help?', 'What are you best at?', 'What makes you nervous?', 'Who is the funniest person you’ve met?', 'What weird or useless talent do you have?', 'What are some strange beliefs that some people have?', 'Who would be the worst person to be stuck in an elevator with? How about the best person to be stuck in an elevator with?', 'What was the best birthday wish or gift you’ve ever received?']

helptext = """
Well, I can do a trick or two. Just read them all. My prefix is `~`

**Moderation**
`kick`, `ban`, `mute`, `unmute`, `clear`, `say + (channel name) + your message`

**Useful**
`ping`, `av + (mention User)`, `dict + (word)`, `wiki + (word)`, `wlist + (word)`, `corona + (country)`, `weather + (city/country)`

**Useful 2**
`news`, `urand`, `urban + (word)`, `advice`, `topic`, `quotes`, `facts`, `mshoes`, `fshoes`

**Fun**
`memes`, `dogs`, `cats`, `words`, `cheemify + (word)`, `owofy + (word)`, `emojify + (word)`, `zalgofy + (word)`, `flip`, `djoke`, `ball + (your question)`, `randpic`


**Convert Youtube URL to music (.m4a)**
`youtube + (youtube url)`

**MASS PING**
`super + (user)`

**Image Manipulation**
`deepfry + (attachment)`, `bnw + (attachment)`

**Anime**
`neko`, `moe`, `dans`

**One Piece Manga Chapter Summaries**
`op + (chapter)`

**Interactions (Mention a user!)**
`hug`, `kiss`, `pat`, `slap`, `cuddle`, `baka`, `smug`, `ratewaifu`

**NSFW**
`blowjob`, `fuck`, `spank`, `moe`, `dans`, `neko`, `rnsfw`

**Reddit/4chan**
`rrand + (subreddit)`, `rrising`, `rsubpost`, `rhot + (subreddit)`, `rnew + (subreddit)`, `rnsfw`, `fourch`

**Makeup**
`lipstick`, `lipliner`, `mascara`, `foundation`, `eyeliner`, `blush`, `polish`



"""

#changes - op (one piece summary), 

"""
**Music (Still in construction)**
`play + (youtube url)`, `stop`, `queue + (youtube url)`, `resume`, `view`, `pause`, `leave`
"""